# Generated by Django 2.0.7 on 2018-07-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('webpage', models.CharField(max_length=255)),
            ],
        ),
    ]
