# Generated by Django 2.0.7 on 2018-07-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRunner',
        ),
    ]
